# Generated by Django 2.2.7 on 2020-01-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_code', models.IntegerField(verbose_name='行政區代碼')),
                ('dept_name', models.CharField(max_length=200, verbose_name='行政區名稱')),
            ],
            options={
                'verbose_name': '行政區',
                'verbose_name_plural': '行政區',
            },
        ),
    ]
